### ISSUE TITLE
Fake chrome not working

### ISSUE THREAD

**Issue by firzok** [fwouts/talk-browser-extension-demo#2]
Hi, I followed your talk and added the Fake chrome to make development faster but it doesn't seem to work. This is the error I am getting. 

P.S: I didn't knew any other way to reach you and get an answer. 

![image](https://user-images.githubusercontent.com/37250472/86379633-83cb0400-bca4-11ea-925a-0caa177a71df.png)

**Comment by fwouts** [comment]
Hi @firzok, could you share the code you used for the fake chrome? Looking at your screenshot, it looks like you may be calling some methods that you haven't defined in there. Could you also share the code where you call `chrome.[something].addListener`?

**Comment by firzok-aai** [comment]
I copied the exact code from your talk. If you want I can copy-paste that but you can easily find it I guess. Also, it works fine when I run the code from your repository but that's in Typescript and I don't want to change from JS to TS.

**Comment by firzok** [comment]
I copied the exact code from your talk. If you want I can copy-paste that but you can easily find it I guess. Also, it works fine when I run the code from your repository but that's in Typescript and I don't want to change from JS to TS.

**Comment by fwouts** [comment]
Thanks for the extra details. It sounds like a difference in configuration. Could you check that:
- `process.env.NODE_ENV` is indeed set to `development` (otherwise [this line](https://github.com/fwouts/talk-browser-extension-demo/blob/1aefbbe77788c16c5cd25768d235def278d0afcd/src/chrome.ts#L8) won't kick in)
- also maybe do a `console.log(chrome)` to make sure the object is what you expect it to be?

**Comment by firzok** [comment]
I deleted that folder because it wasn't working and have moved to TS. Thank you for your help
